### PR TITLE
Use header for auth

### LINKED ISSUE #17: Move API key auth to headers

### PR DESCRIPTION
**Pull request by AMeng**
Fixes #17
Based on https://github.com/fullcontact/fullcontact-api-ruby/pull/39

### CODE REVIEW

**Comment by AMeng** [comment]
@Xorlev PTAL

**Comment by Xorlev** [comment]
Looks good, I'll merge it once I'm in office.

**Comment by swanandp** [comment]
Thanks @Ameng 

I'm really sorry for opening a PR with no tests and then not following it up.

**Comment by AMeng** [comment]
@swanandp no worries, thanks for the contribution!

**Comment by Xorlev** [comment]
Released in 0.15.0

**Pull request merged**
