### PR TITLE
Get many people in a single batch request

### PR DESCRIPTION
**Pull request by frausto**
Just throwing this out there if you want to merge it in. I added the #people method to allow you to get multiple people in a single batch request.

Also added xml to the specs

### CODE REVIEW

**Comment by RajRoR** [comment]
When we can expect it to be merged and we can get the feature of batch requests?

**Comment by RajRoR** [comment]
@frausto, will it support batch request other than twitter and email too? Will it work for facebookId, facebookUsername etc?

**Comment by Xorlev** [comment]
Hi @RajRoR, the Batch API internally is fairly unsupported. Until we're confident that we're 1) going to keep it and 2) going to fix outstanding issues with it (namely around rate limiting headers) I've been punting on merging this.

**Comment by jbaylin** [comment]
@Xorlev Any update on this?

**Comment by Xorlev** [comment]
We consider the Batch API in its current format deprecated internally. Until we have a better batch runner (we certainly want batch calls still!) we'll close this.

**Comment by ACPK** [comment]
@Xorlev - Is it still unsupported as I keep hitting the 60 request/min limit?

**Comment by Xorlev** [comment]
@ACPK the batch API does not sidestep your rate limit. You are still limited to 60 person lookups a minute, regardless of whether it's in batch or individual calls.

**Pull request closed without merging**
